apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-core-status-service
  namespace: fint-core
spec:
  port: 8080
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-core-status-service:latest
  kafka:
    enabled: true
    acls:
      - topic: '*.fint-core.event.*'
        permission: admin
  ingress:
    enabled: true
    routes:
      - host: core-status.fintlabs.no
        path: /beta
  env:
    - name: JAVA_TOOL_OPTIONS
      value: '-XX:+ExitOnOutOfMemoryError -Xmx525M'
  resources:
    limits:
      memory: "1Gi"
      cpu: "500m"
    requests:
      memory: "500Mi"
      cpu: "100m"