spring:
  jpa:
    properties:
      jdbc:
        time_zone: UTC
        lob:
          non_contextual_creation: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
      enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${fint.database.url}
    username: ${fint.database.username}
    password: ${fint.database.password}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: ${fint.database.username}

event:
  database:
    cleanupTime: "0 55 14 * * ?"
  cacheFlushAndRefill: "0 57 14 * * ?"
