fint:
  prometheus:
    baseUrl: "http://prometheus-stack-prometheus.flais-system:80"
    query:
      memory: 'sum by (pod, namespace) (container_memory_usage_bytes{pod=~".*fint-core-consumer.*"}) * on (pod, namespace) group_left (uid) kube_pod_info{pod=~".*fint-core-consumer.*"}'
      restarts: 'sum by (pod, namespace) (  kube_pod_container_status_restarts_total{pod=~".*fint-core-consumer.*"})* on (pod, namespace) group_left(uid) (  kube_pod_info{pod=~".*fint-core-consumer.*"})'

  security:
    open-paths: |
      /actuator/prometheus
    org-id: false
    component: false
  heartbeat:
    check-rate: 10000
  kafka:
    application-id: fint-core-status-service

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
  kafka:
    consumer:
      group-id: ${fint.kafka.application-id}
  profiles:
    include: db

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"

logging:
  level:
    no.fintlabs.kafka: warn
    org.springframework.kafka: warn
    org.apache.kafka: warn
    no.fintlabs.event: debug
    no.fintlabs.page: info