fint:
  kafka:
    application-id: status-service
    enable-ssl: false
    default-replicas: 1
    topic:
      org-id: fintlabs.no
      domain-context: fint-core

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
  webflux:
    base-path: /status
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: status-service
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: none
    hikari:
      schema: ${fint.database.username}
  flyway:
    locations: classpath:db/migration/
    lock-retry-count: 300

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

