fint:
  security:
    org-id: false
    component: false
  heartbeat:
    check-rate: 10000
  kafka:
    application-id: fint-core-status-service

spring:
  kafka:
    consumer:
      group-id: ${fint.kafka.application-id}