fint:
  heartbeat:
    check-rate: 10000
  kafka:
    application-id: fint-core-status-service
    enable-ssl: false
    default-replicas: 1

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: fint-core-status-service