fint:
  kafka:
    application-id: status-service
    enable-ssl: true
    topic:
      org-id: fintlabs.no
      domain-context: fint-core

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
  webflux:
    base-path: /status
  kafka:
    consumer:
      group-id: status-service
  profiles:
    include:
      - db
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

