fint:
  kafka:
    application-id: fint-core-status-service
    enable-ssl: false
    default-replicas: 1

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: fint-core-status-service