fint:
  kafka:
    application-id: status-service
    enable-ssl: true

spring:
  webflux:
    base-path: /status
  kafka:
    consumer:
      group-id: status-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
  datasource:
    url: jdbc:postgresql://localhost:5432/fint_core_status_service
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

