fint:
  prometheus:
    baseUrl: "http://localhost:52517"
    query:
      memory: 'sum by (pod, namespace) (container_memory_usage_bytes{pod=~".*fint-core-consumer.*"}) * on (pod, namespace) group_left (uid) kube_pod_info{pod=~".*fint-core-consumer.*"}'
      restarts: 'sum by (pod, namespace) (  kube_pod_container_status_restarts_total{pod=~".*fint-core-consumer.*"})* on (pod, namespace) group_left(uid) (  kube_pod_info{pod=~".*fint-core-consumer.*"})'

  security:
    org-id: false
    component: false
  heartbeat:
    check-rate: 10000
  kafka:
    application-id: fint-core-status-service
    enable-ssl: false
    default-replicas: 1
  spring:
    kafka:
      consumer:
        group-id: ${fint.kafka.application-id}

spring:
  jpa:
    properties:
      jdbc:
        lob:
      enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5436/fint-core-status-service
    username: postgres
    password: password
    hikari:
      schema: public
logging:
  level:
    no.fintlabs.kafka: OFF
    org.springframework.kafka: info
    org.apache.kafka: OFF