fint:
  kafka:
    application-id: status-service
    enable-ssl: true
    topic:
      org-id: fintlabs.no
      domain-context: fint-core

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
  webflux:
    base-path: /status
  kafka:
    consumer:
      group-id: status-service
  datasource:
    url: ${fint.database.url}
    username: ${fint.database.username}
    password: ${fint.database.password}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

