fint:
  prometheus:
    baseUrl: "http://prometheus-prometheus-stack-prometheus-0.flais-system.svc.cluster.local:9090/api/v1/query?"
    query: 'query=kube_pod_container_status_restarts_total{pod=~".*fint-core-consumer.*"}'

  security:
    org-id: false
    component: false
  heartbeat:
    check-rate: 10000
  kafka:
    application-id: fint-core-status-service

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
  kafka:
    consumer:
      group-id: ${fint.kafka.application-id}
  profiles:
    include: db

logging:
  level:
    no.fintlabs.kafka: warn
    org.springframework.kafka: warn
    org.apache.kafka: warn
    no.fintlabs.event: debug
    no.fintlabs.page: info