apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
patches:
  - patch: |-
      - op: add
        path: "/spec/url/hostname"
        value: "beta.felleskomponent.no"
    target:
      kind: Application
      name: fint-core-status-service
