apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-core-status-service
  namespace: fint-core
spec:
  port: 8080
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-core-status-service:latest
  kafka:
    enabled: true
    acls:
      - topic: '*.fint-core.event.*'
        permission: admin
  observability:
    metrics:
      enabled: true
      port: "8080"
      path: /api/actuator/prometheus
  database:
    database: fint-core
  ingress:
    routes:
      - host: core-status.fintlabs.no
        path: /api
  env:
    - name: JAVA_TOOL_OPTIONS
      value: '-XX:+ExitOnOutOfMemoryError -Xmx525M'
    - name: spring.webflux.base-path
      value: /api
  resources:
    limits:
      memory: "1Gi"
      cpu: "1"
    requests:
      memory: "500Mi"
      cpu: "100m"