spring:
  application:
    name: fint-core-status-service
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${fint.database.url}
    username: ${fint.database.username}
    password: ${fint.database.password}
    hikari:
      schema: ${fint.database.username}
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    default-schema: ${fint.database.username}
  kafka:
    listener:
      auto-startup: ${fint.status.enabled:true}
    security:
      protocol: SSL
    consumer:
      group-id: fint-core-status-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  mvc:
    problemdetails:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam

springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    path: /api/v1/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

logging:
  level:
    root: INFO
    org.apache.kafka: WARN
