fint:
  kafka:
    enable-ssl: false
    default-replicas: 1

spring:
  flyway:
    default-schema: public
  datasource:
    url: jdbc:postgresql://localhost:5436/fint-core-status-service
    username: postgres
    password: password
    hikari:
      schema: public

logging:
  level:
    no.fintlabs.kafka: OFF
    org.springframework.kafka: info
    org.apache.kafka: OFF
