apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-core-status-service
  namespace: fintlabs-no
spec:
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-core-status-service:sha-0000000
  resources:
    limits:
      memory: "512Mi"
      cpu: "1"
    requests:
      memory: "128Mi"
      cpu: "100m"
  kafka:
    enabled: true
    acls:
      - permission: read
        topic: 'fintlabs-no.fint-core.*'
  database:
    database: fint-core
  ingress:
    enabled: true
  env:
    - name: JAVA_TOOLS_OPTIONS
      value: '-XX:+ExitOnOutOfMemoryError -Xmx480M'
    - name: fint.kafka.topic.domain-context
      value: 'fint-core'
    - name: fint.kafka.topic.org-id
      value: 'fintlabs-no'
  url:
    basePath: /status