apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flais.yaml
commonLabels:
  app.kubernetes.io/name: fint-core-status-service
  app.kubernetes.io/instance: fint-core-status-service_fintlabs_no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: status-service
  app.kubernetes.io/part-of: fint-core
  fintlabs.no/team: core
  fintlabs.no/org-id: fintlabs.no
