/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/contracts/{id}/mute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["mute"];
        post?: never;
        delete: operations["unmute"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/syncs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/syncs/{corrId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/syncs/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["countNew"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["orgs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["model"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{corrId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["countNew_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contracts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MuteRequest: {
            reason: string | null;
            /** Format: date-time */
            mutedUntil: string | null;
        };
        CapabilityView: {
            domainName: string;
            packageName: string;
            resourceName: string;
            /** Format: int32 */
            fullSyncIntervalDays: number;
            deltaSyncInterval: string | null;
            /** Format: date-time */
            lastFullSyncAt: string | null;
            /** @enum {string} */
            fullSync: "OK" | "WAITING" | "OVERDUE" | "NEVER";
        };
        ContractDetail: {
            /** Format: int64 */
            id: number;
            orgId: string;
            mainOrgId: string;
            username: string;
            adapterId: string;
            /** Format: int32 */
            heartbeatIntervalMinutes: number;
            /** Format: date-time */
            firstRegisteredAt: string;
            /** Format: date-time */
            registeredAt: string;
            /** Format: date-time */
            lastHeartbeatAt: string | null;
            /** @enum {string} */
            heartbeat: "OK" | "STOPPED" | "NEVER";
            mute: components["schemas"]["MuteView"] | null;
            capabilities: components["schemas"]["CapabilityView"][];
            eventCapabilities: components["schemas"]["EventCapabilityView"][];
        };
        EventCapabilityView: {
            domainName: string;
            packageName: string;
            resourceName: string;
            operations: string[];
        };
        MuteView: {
            mutedBy: string;
            reason: string | null;
            /** Format: date-time */
            mutedAt: string;
            /** Format: date-time */
            mutedUntil: string | null;
        };
        PageResponseSyncSummary: {
            items: components["schemas"]["SyncSummary"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            total: number;
        };
        SyncSummary: {
            corrId: string;
            /** @enum {string} */
            type: "FULL" | "DELTA" | "DELETE";
            orgId: string;
            domainName: string;
            packageName: string;
            resourceName: string;
            adapterId: string;
            /** Format: int32 */
            totalPages: number;
            /** Format: int32 */
            pagesReceived: number;
            /** Format: int64 */
            totalSize: number;
            /** Format: int64 */
            entitiesReceived: number;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            lastPageAt: string;
            /** Format: date-time */
            completedAt: string | null;
            /** @enum {string} */
            state: "COMPLETED" | "RUNNING" | "STALLED";
        };
        SyncDetail: {
            sync: components["schemas"]["SyncSummary"];
            pages: components["schemas"]["SyncPageView"][];
        };
        SyncPageView: {
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: date-time */
            receivedAt: string;
        };
        CountResponse: {
            /** Format: int64 */
            count: number;
        };
        OrgNode: {
            orgId: string;
            subOrgs: string[];
        };
        ModelDomain: {
            name: string;
            packages: components["schemas"]["ModelPackage"][];
        };
        ModelPackage: {
            name: string;
            resources: string[];
        };
        Info: {
            enabled: boolean;
        };
        EventSummary: {
            corrId: string;
            orgId: string;
            domainName: string | null;
            packageName: string | null;
            resourceName: string | null;
            operationType: string | null;
            /** Format: date-time */
            createdAt: string | null;
            /** Format: date-time */
            expiresAt: string | null;
            /** Format: date-time */
            receivedAt: string;
            /** Format: date-time */
            handledAt: string | null;
            /** @enum {string} */
            status: "PENDING" | "ANSWERED" | "FAILED" | "REJECTED" | "CONFLICTED" | "EXPIRED";
            reason: string | null;
            answeredBy: string | null;
            candidates: string[];
        };
        PageResponseEventSummary: {
            items: components["schemas"]["EventSummary"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            total: number;
        };
        Candidate: {
            /** Format: int64 */
            contractId: number;
            username: string;
            orgId: string;
            /** @enum {string} */
            heartbeat: "OK" | "STOPPED" | "NEVER";
            muted: boolean;
        };
        EventDetail: {
            event: components["schemas"]["EventSummary"];
            adapterId: string | null;
            candidates: components["schemas"]["Candidate"][];
        };
        Dashboard: {
            /** Format: date-time */
            generatedAt: string;
            totals: components["schemas"]["DashboardTotals"];
            orgs: components["schemas"]["OrgHealth"][];
        };
        DashboardTotals: {
            /** Format: int32 */
            heartbeatStopped: number;
            /** Format: int32 */
            heartbeatNever: number;
            /** Format: int32 */
            fullSyncOverdue: number;
            /** Format: int32 */
            fullSyncNever: number;
            /** Format: int32 */
            eventsExpired: number;
            /** Format: int32 */
            eventsPendingLong: number;
            /** Format: int32 */
            orgsWithProblems: number;
        };
        OrgHealth: {
            orgId: string;
            /** Format: int32 */
            contracts: number;
            /** Format: int32 */
            muted: number;
            /** Format: int32 */
            heartbeatStopped: number;
            /** Format: int32 */
            heartbeatNever: number;
            /** Format: int32 */
            fullSyncOverdue: number;
            /** Format: int32 */
            fullSyncNever: number;
            /** Format: int32 */
            eventsExpired: number;
            /** Format: int32 */
            eventsPendingLong: number;
            subOrgs: components["schemas"]["OrgHealth"][];
            hasProblems: boolean;
        };
        ContractPage: {
            items: components["schemas"]["ContractSummary"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            total: number;
            counts: {
                [key: string]: number;
            };
        };
        ContractSummary: {
            /** Format: int64 */
            id: number;
            orgId: string;
            mainOrgId: string;
            username: string;
            /** @enum {string} */
            heartbeat: "OK" | "STOPPED" | "NEVER";
            /** Format: date-time */
            lastHeartbeatAt: string | null;
            /** Format: int32 */
            fullSyncOverdue: number;
            /** Format: int32 */
            fullSyncNever: number;
            /** Format: int32 */
            capabilities: number;
            muted: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    mute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MuteRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ContractDetail"];
                };
            };
        };
    };
    unmute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: {
                type?: "FULL" | "DELTA" | "DELETE" | "ALL";
                from?: string;
                to?: string;
                state?: "COMPLETED" | "RUNNING" | "STALLED";
                org?: string;
                corrId?: string;
                domain?: string;
                package?: string;
                resource?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseSyncSummary"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corrId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SyncDetail"];
                };
            };
        };
    };
    countNew: {
        parameters: {
            query: {
                since: string;
                type?: "FULL" | "DELTA" | "DELETE" | "ALL";
                state?: "COMPLETED" | "RUNNING" | "STALLED";
                org?: string;
                corrId?: string;
                domain?: string;
                package?: string;
                resource?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CountResponse"];
                };
            };
        };
    };
    orgs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrgNode"][];
                };
            };
        };
    };
    model: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ModelDomain"][];
                };
            };
        };
    };
    info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Info"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                status?: "PENDING" | "EXPIRED" | "ANSWERED" | "ERRORS";
                from?: string;
                to?: string;
                org?: string;
                corrId?: string;
                domain?: string;
                package?: string;
                resource?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseEventSummary"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corrId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventDetail"];
                };
            };
        };
    };
    countNew_1: {
        parameters: {
            query: {
                since: string;
                status?: "PENDING" | "EXPIRED" | "ANSWERED" | "ERRORS";
                org?: string;
                corrId?: string;
                domain?: string;
                package?: string;
                resource?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CountResponse"];
                };
            };
        };
    };
    dashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Dashboard"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                q?: string;
                filter?: "ALL" | "HEARTBEAT_STOPPED" | "HEARTBEAT_NEVER" | "FULL_SYNC_OVERDUE" | "FULL_SYNC_NEVER" | "MUTED";
                sort?: "HEALTH" | "ORG" | "USERNAME" | "HEARTBEAT" | "FULL_SYNC" | "CAPABILITIES";
                direction?: "ASC" | "DESC";
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ContractPage"];
                };
            };
        };
    };
    get_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ContractDetail"];
                };
            };
        };
    };
}
